#Update all the sections by editing the data.yml file inside _data folder.

# Site Settings
title: Wayne Burlingame
url: 'https://wayneburlingame.com'

#change it according to your repository name
# disabling since we are using a custom domain
baseurl: '/shiroscout' 

description: A beautiful Jekyll theme for creating resume
# Style will be applied only after restarting the build or serve. Just choose one of the options.
theme_skin: green # blue turquoise green berry orange ceramic
chrome_mobile_color: #006699

# Tracker
#analytics: UA-83979019-1

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
compress-site: yes

encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development

# Development Settings
port: 4000
host: 0.0.0.0
safe: false
